/**
 * @oweibo/module-scaffolding
 *
 * Generates the base project scaffold: directory structure, package.json,
 * tsconfig, ESLint config, Prettier, .gitignore, Docker files, and CI configs.
 * Always the first module to run — all other modules build on top of its output.
 *
 * Implements IModuleGenerator (core-contracts only — no core-engine imports).
 */
import type {
  IModuleGenerator,
  IModuleManifest,
  IBlueprintReader,
  IGeneratorAPI,
  ArtifactBundle,
  ArtifactFile,
  ValidationResult,
  ScaffoldInput,
} from '@oweibo/core-contracts';
import { createHash } from 'crypto';

function checksum(content: string): string {
  return createHash('sha256').update(content, 'utf-8').digest('hex');
}

function file(path: string, content: string): ArtifactFile {
  return { path, content, encoding: 'utf-8', checksum: checksum(content) };
}

// ─── Manifest ────────────────────────────────────────────────────────────────

const MANIFEST: IModuleManifest = {
  name: 'module-scaffolding',
  version: '0.1.0',
  coreContractsVersion: '>=0.1.0',
  emits: ['scaffolding:completed'],
  consumes: [],
  knowledgeArtifactPath: 'knowledge/module-scaffolding.json',
};

// ─── Template builders ───────────────────────────────────────────────────────

function buildPackageJson(input: ScaffoldInput): string {
  const stackDeps: Record<string, Record<string, string>> = {
    t3: {
      next: '^14.0.0', react: '^18.0.0', 'react-dom': '^18.0.0',
      '@trpc/server': '^11.0.0', '@trpc/client': '^11.0.0',
    },
    nextjs: { next: '^14.0.0', react: '^18.0.0', 'react-dom': '^18.0.0' },
    express: { express: '^4.18.0', cors: '^2.8.5', helmet: '^7.0.0' },
    mern: { express: '^4.18.0', mongoose: '^8.0.0', react: '^18.0.0' },
    laravel: {},
    django: {},
  };
  const deps = stackDeps[input.stack] ?? {};

  return JSON.stringify({
    name: input.appName.toLowerCase().replace(/\s+/g, '-'),
    version: '0.1.0',
    private: true,
    scripts: {
      dev: input.stack === 'nextjs' || input.stack === 't3' ? 'next dev' : 'ts-node-dev src/index.ts',
      build: input.stack === 'nextjs' || input.stack === 't3' ? 'next build' : 'tsc',
      start: input.stack === 'nextjs' || input.stack === 't3' ? 'next start' : 'node dist/index.js',
      test: 'jest --passWithNoTests',
      lint: 'eslint . --ext .ts,.tsx',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      ...deps,
      zod: '^3.23.0',
    },
    devDependencies: {
      typescript: '^5.5.0',
      '@types/node': '^20.0.0',
      jest: '^29.0.0',
      'ts-jest': '^29.0.0',
      '@types/jest': '^29.0.0',
      eslint: '^8.0.0',
      '@typescript-eslint/eslint-plugin': '^7.0.0',
      '@typescript-eslint/parser': '^7.0.0',
      prettier: '^3.0.0',
      rimraf: '^5.0.0',
    },
  }, null, 2);
}

function buildTsConfig(input: ScaffoldInput): string {
  const isNext = input.stack === 'nextjs' || input.stack === 't3';
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      lib: isNext ? ['dom', 'dom.iterable', 'esnext'] : ['ES2022'],
      module: isNext ? 'esnext' : 'Node16',
      moduleResolution: isNext ? 'bundler' : 'Node16',
      jsx: isNext ? 'preserve' : undefined,
      strict: true,
      noUncheckedIndexedAccess: true,
      exactOptionalPropertyTypes: true,
      outDir: './dist',
      rootDir: './src',
      declaration: true,
      declarationMap: true,
      sourceMap: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
    },
    include: ['src'],
    exclude: ['node_modules', 'dist'],
  }, null, 2);
}

function buildDockerfile(input: ScaffoldInput): string {
  return `# Generated by oweibo module-scaffolding
FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM base AS builder
RUN npm ci
COPY . .
RUN npm run build

FROM base AS runner
COPY --from=builder /app/dist ./dist
EXPOSE 3000
ENV NODE_ENV=production
CMD ["node", "dist/index.js"]
`;
}

function buildHealthEndpoint(input: ScaffoldInput): string {
  return `// health.ts — required by SmokeTestStage (§8b)
import { Router } from 'express';

const router = Router();

router.get('/health', (_req, res) => {
  res.json({
    status: 'ok',
    app: '${input.appName}',
    timestamp: new Date().toISOString(),
    version: process.env.npm_package_version ?? '0.1.0',
  });
});

export default router;
`;
}

function buildGitIgnore(): string {
  return `node_modules/
dist/
.env
.env.local
*.log
.DS_Store
coverage/
.next/
out/
`;
}

function buildEslintConfig(): string {
  return JSON.stringify({
    root: true,
    parser: '@typescript-eslint/parser',
    plugins: ['@typescript-eslint'],
    extends: [
      'eslint:recommended',
      'plugin:@typescript-eslint/recommended',
      'plugin:@typescript-eslint/recommended-requiring-type-checking',
    ],
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  }, null, 2);
}

function buildScaffoldingTest(input: ScaffoldInput): string {
  return `// module-scaffolding.contract.test.ts
// Contract test: verifies scaffold output meets IModuleGenerator contract.
import { ScaffoldingGenerator } from '../index';
import type { IBlueprintReader, IGeneratorAPI, ArtifactBundle } from '@oweibo/core-contracts';

const mockInput = {
  appName: '${input.appName}',
  stack: '${input.stack}' as const,
  database: '${input.database}' as const,
  features: [],
  tenantId: 'test-tenant',
  hardwareProfile: 'core_i5' as const,
};

const mockReader: IBlueprintReader = {
  getScaffoldInput: () => mockInput,
  readFile: async () => null,
  listFiles: async () => [],
};

const files = new Map<string, string>();
const mockApi: IGeneratorAPI = {
  writeFile: async (path, content) => { files.set(path, content); },
  appendFile: async (path, content) => { files.set(path, (files.get(path) ?? '') + content); },
  deleteFile: async (path) => { files.delete(path); },
  runShellCommand: async () => ({ stdout: '', stderr: '', exitCode: 0 }),
  getArchitectOutput: () => undefined,
  getExecutorOutput: () => undefined,
};

describe('ScaffoldingGenerator', () => {
  let bundle: ArtifactBundle;

  beforeAll(async () => {
    const gen = new ScaffoldingGenerator();
    bundle = await gen.generate(mockReader, mockApi);
  });

  it('produces non-empty files array', () => {
    expect(bundle.files.length).toBeGreaterThan(0);
  });

  it('includes package.json', () => {
    const pkg = bundle.files.find(f => f.path === 'package.json');
    expect(pkg).toBeDefined();
    expect(JSON.parse(pkg!.content)).toHaveProperty('scripts.test');
  });

  it('includes tsconfig.json', () => {
    expect(bundle.files.find(f => f.path === 'tsconfig.json')).toBeDefined();
  });

  it('includes a health endpoint', () => {
    expect(bundle.files.find(f => f.path.includes('health'))).toBeDefined();
  });

  it('passes validation', () => {
    const gen = new ScaffoldingGenerator();
    const result = gen.validate(bundle);
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });
});
`;
}

// ─── Generator class ─────────────────────────────────────────────────────────

export class ScaffoldingGenerator implements IModuleGenerator {
  readonly manifest: IModuleManifest = MANIFEST;

  async generate(reader: IBlueprintReader, api: IGeneratorAPI): Promise<ArtifactBundle> {
    const input = reader.getScaffoldInput();
    const files: ArtifactFile[] = [];

    const fileMap: Record<string, string> = {
      'package.json':             buildPackageJson(input),
      'tsconfig.json':            buildTsConfig(input),
      'Dockerfile':               buildDockerfile(input),
      '.gitignore':               buildGitIgnore(),
      '.eslintrc.json':           buildEslintConfig(),
      'src/routes/health.ts':     buildHealthEndpoint(input),
      '.env.example':             `NODE_ENV=development\nPORT=3000\nDATABASE_URL=\nREDIS_URL=\n`,
      'README.md':                `# ${input.appName}\n\nGenerated by oweibo.\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    };

    for (const [path, content] of Object.entries(fileMap)) {
      await api.writeFile(path, content);
      files.push(file(path, content));
    }

    const testContent = buildScaffoldingTest(input);
    await api.writeFile('src/__tests__/scaffolding.contract.test.ts', testContent);
    const testFile = file('src/__tests__/scaffolding.contract.test.ts', testContent);

    return {
      files,
      testFiles: [testFile],
      dbMigrations: [],
      k8sManifests: [],
      docFiles: [],
      knowledgeArtifact: {
        moduleName: 'module-scaffolding',
        version: MANIFEST.version,
        generatedAt: new Date().toISOString(),
        domainDescription: 'Base project scaffold providing directory structure, tooling config, and health endpoints.',
        entities: [],
        endpoints: [{ method: 'GET', path: '/health', filePath: 'src/routes/health.ts', description: 'Health check endpoint' }],
        emittedEvents: [],
        consumedEvents: [],
        invariants: [{ description: '/health must return 200 with status:ok', source: 'annotation', filePath: 'src/routes/health.ts' }],
        extensionPoints: [],
        userFlows: [{ name: 'Check service health', actor: 'DevOps', steps: ['GET /health'], outcome: 'Service status confirmed as ok' }],
        glossary: [{ term: 'Scaffold', definition: 'The base project structure that all other modules build upon' }],
        exampleUsages: [],
      },
      signature: '',
    };
  }

  validate(bundle: ArtifactBundle): ValidationResult {
    const errors: Array<{ code: string; message: string; filePath?: string }> = [];

    if (bundle.files.length === 0) {
      errors.push({ code: 'EMPTY_BUNDLE', message: 'Scaffold produced no files' });
    }
    if (!bundle.files.find(f => f.path === 'package.json')) {
      errors.push({ code: 'MISSING_PACKAGE_JSON', message: 'package.json is required' });
    }
    if (!bundle.files.find(f => f.path === 'tsconfig.json')) {
      errors.push({ code: 'MISSING_TSCONFIG', message: 'tsconfig.json is required' });
    }
    if (!bundle.files.find(f => f.path.includes('health'))) {
      errors.push({ code: 'MISSING_HEALTH_ENDPOINT', message: 'A /health endpoint file is required (SmokeTestStage gate)' });
    }
    if (bundle.testFiles.length === 0) {
      errors.push({ code: 'MISSING_TESTS', message: 'At least one test file is required (TDD gate)' });
    }

    return { valid: errors.length === 0, errors, warnings: [] };
  }
}

export default ScaffoldingGenerator;
