/**
 * D.0 (domain-depth): v1 platform domain catalog — the bundled fallback.
 *
 * This is the source of truth used when `DomainRegistry` is constructed
 * without a database connection (in-process, tests, CLI). When the
 * registry is wired with a pg Pool, the table contents take precedence
 * and this catalog acts as the bootstrap seed (matched 1:1 to the rows
 * inserted by migration `20260521_000032_dd_domain_registry.sql`).
 *
 * Keep this file 1:1 in sync with the migration's INSERT block. Adding a
 * domain requires both an entry here and a migration; the test asserts
 * the count matches.
 */
import type { DomainCatalogEntry } from '@oweibo/core-contracts';

export const V1_DOMAIN_CATALOG: readonly DomainCatalogEntry[] = [
  {
    slug: 'fintech',
    displayName: 'Financial services',
    description: 'Banking, payments, lending, capital markets',
    category: 'regulated',
    compliancePostures: ['PCI-DSS', 'SOC2'],
    archetypeRoles: ['CFO', 'Head of Risk', 'Compliance Officer'],
    typicalConnectors: ['stripe', 'plaid'],
    canonicalVerbiage: ['payment', 'reconciliation', 'ledger', 'settlement'],
    registryVersion: '1.0.0',
    maturity: 'beta',
    depthTargets: {},
  },
  {
    slug: 'healthcare',
    displayName: 'Healthcare',
    description: 'Provider, payer, clinical research',
    category: 'regulated',
    compliancePostures: ['HIPAA', 'SOC2'],
    archetypeRoles: ['Chief Medical Officer', 'Compliance Officer', 'Privacy Officer'],
    typicalConnectors: ['epic', 'twilio'],
    canonicalVerbiage: ['patient', 'encounter', 'diagnosis', 'phi'],
    registryVersion: '1.0.0',
    maturity: 'beta',
    depthTargets: {},
  },
  {
    slug: 'legal',
    displayName: 'Legal',
    description: 'Law firms, in-house counsel, regulatory affairs',
    category: 'regulated',
    compliancePostures: ['SOC2'],
    archetypeRoles: ['General Counsel', 'Compliance Officer'],
    typicalConnectors: [],
    canonicalVerbiage: ['matter', 'docket', 'discovery', 'privilege'],
    registryVersion: '1.0.0',
    maturity: 'experimental',
    depthTargets: {},
  },
  {
    slug: 'ml-research',
    displayName: 'ML research',
    description: 'Academic and industrial ML R&D',
    category: 'technical',
    compliancePostures: [],
    archetypeRoles: ['PI', 'Lab Director', 'ML Lead'],
    typicalConnectors: ['weights-biases', 'huggingface'],
    canonicalVerbiage: ['experiment', 'eval', 'dataset', 'checkpoint'],
    registryVersion: '1.0.0',
    maturity: 'beta',
    depthTargets: {},
  },
  {
    slug: 'devops',
    displayName: 'DevOps / Platform',
    description: 'SRE, infrastructure, platform engineering',
    category: 'technical',
    compliancePostures: ['SOC2'],
    archetypeRoles: ['Platform Lead', 'SRE Manager', 'CTO'],
    typicalConnectors: ['github', 'datadog'],
    canonicalVerbiage: ['deploy', 'incident', 'rollback', 'sla', 'observability'],
    registryVersion: '1.0.0',
    maturity: 'general_availability',
    depthTargets: {},
  },
  {
    slug: 'ecommerce',
    displayName: 'E-commerce',
    description: 'Retail, marketplace, fulfillment',
    category: 'professional',
    compliancePostures: ['PCI-DSS'],
    archetypeRoles: ['Head of Commerce', 'Head of Fulfillment'],
    typicalConnectors: ['shopify', 'stripe'],
    canonicalVerbiage: ['inventory', 'order', 'fulfillment', 'sku'],
    registryVersion: '1.0.0',
    maturity: 'beta',
    depthTargets: {},
  },
  {
    slug: 'gaming',
    displayName: 'Gaming',
    description: 'Game development, live-ops, monetization',
    category: 'creative',
    compliancePostures: [],
    archetypeRoles: ['Game Director', 'Live-Ops Lead'],
    typicalConnectors: [],
    canonicalVerbiage: ['retention', 'monetization', 'live-ops', 'cohort'],
    registryVersion: '1.0.0',
    maturity: 'experimental',
    depthTargets: {},
  },
  {
    slug: 'media',
    displayName: 'Media / Publishing',
    description: 'Editorial, content production, distribution',
    category: 'creative',
    compliancePostures: [],
    archetypeRoles: ['Editor-in-Chief', 'Head of Distribution'],
    typicalConnectors: [],
    canonicalVerbiage: ['editorial', 'distribution', 'content', 'rights'],
    registryVersion: '1.0.0',
    maturity: 'experimental',
    depthTargets: {},
  },
  {
    slug: 'manufacturing',
    displayName: 'Manufacturing',
    description: 'Industrial, supply chain, operations',
    category: 'professional',
    compliancePostures: ['SOC2'],
    archetypeRoles: ['Plant Manager', 'Supply Chain Lead'],
    typicalConnectors: [],
    canonicalVerbiage: ['mrp', 'inventory', 'supply', 'production'],
    registryVersion: '1.0.0',
    maturity: 'experimental',
    depthTargets: {},
  },
  {
    slug: 'education',
    displayName: 'Education',
    description: 'K-12, higher ed, ed-tech',
    category: 'professional',
    compliancePostures: ['FERPA'],
    archetypeRoles: ['Dean', 'Curriculum Lead'],
    typicalConnectors: [],
    canonicalVerbiage: ['curriculum', 'enrollment', 'assessment', 'grade'],
    registryVersion: '1.0.0',
    maturity: 'experimental',
    depthTargets: {},
  },
];
