/**
 * @oweibo/module-datalayer
 *
 * Generates the database access layer: Prisma schema, migrations, typed
 * repository classes, and connection pooling config. Supports PostgreSQL,
 * MySQL, and SQLite.
 *
 * Implements IModuleGenerator (core-contracts only — no core-engine imports).
 */
import type {
  IModuleGenerator,
  IModuleManifest,
  IBlueprintReader,
  IGeneratorAPI,
  ArtifactBundle,
  ArtifactFile,
  ValidationResult,
} from '@oweibo/core-contracts';
import { createHash } from 'crypto';

function checksum(c: string): string { return createHash('sha256').update(c, 'utf-8').digest('hex'); }
function file(path: string, content: string): ArtifactFile {
  return { path, content, encoding: 'utf-8', checksum: checksum(content) };
}

const MANIFEST: IModuleManifest = {
  name: 'module-datalayer',
  version: '0.1.0',
  coreContractsVersion: '>=0.1.0',
  emits: ['datalayer:completed'],
  consumes: ['scaffolding:completed'],
  knowledgeArtifactPath: 'knowledge/module-datalayer.json',
};

const DB_PROVIDERS: Record<string, string> = { postgresql: 'postgresql', mysql: 'mysql', sqlite: 'sqlite' };

function buildPrismaSchema(database: string): string {
  const provider = DB_PROVIDERS[database] ?? 'postgresql';
  const url = database === 'sqlite' ? '"file:./dev.db"' : 'env("DATABASE_URL")';
  return `// prisma/schema.prisma — generated by oweibo module-datalayer
generator client {
  provider = "prisma-client-js"
}
datasource db {
  provider = "${provider}"
  url      = ${url}
}
model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  @@map("users")
}
model AuditLog {
  id         String   @id @default(cuid())
  entityType String
  entityId   String
  action     String
  userId     String?
  metadata   Json?
  createdAt  DateTime @default(now())
  @@index([entityType, entityId])
  @@index([userId])
  @@map("audit_logs")
}
`;
}

function buildDbClient(database: string): string {
  return `// src/db/client.ts — generated by oweibo module-datalayer
import { PrismaClient } from '@prisma/client';
declare global { var __prisma: PrismaClient | undefined; }
const prisma: PrismaClient = global.__prisma ?? new PrismaClient({
  log: process.env.NODE_ENV === 'development' ? ['query', 'warn', 'error'] : ['error'],
});
if (process.env.NODE_ENV !== 'production') global.__prisma = prisma;
export { prisma };
export async function connectDb(): Promise<void> {
  await prisma.$connect();
  console.log('[db] Connected to ${database}');
}
export async function disconnectDb(): Promise<void> { await prisma.$disconnect(); }
`;
}

function buildUserRepository(): string {
  return `// src/db/repositories/UserRepository.ts — generated by oweibo module-datalayer
import type { Prisma, User } from '@prisma/client';
import { prisma } from '../client.js';
export class UserRepository {
  async findById(id: string): Promise<User | null> { return prisma.user.findUnique({ where: { id } }); }
  async findByEmail(email: string): Promise<User | null> { return prisma.user.findUnique({ where: { email } }); }
  async create(data: Prisma.UserCreateInput): Promise<User> { return prisma.user.create({ data }); }
  async update(id: string, data: Prisma.UserUpdateInput): Promise<User> { return prisma.user.update({ where: { id }, data }); }
  async delete(id: string): Promise<void> { await prisma.user.delete({ where: { id } }); }
  async list(pagination: { page: number; limit: number }): Promise<{ items: User[]; total: number }> {
    const skip = (pagination.page - 1) * pagination.limit;
    const [items, total] = await prisma.$transaction([
      prisma.user.findMany({ skip, take: pagination.limit, orderBy: { createdAt: 'desc' } }),
      prisma.user.count(),
    ]);
    return { items, total };
  }
}
`;
}

function buildDatalayerTest(): string {
  return `// src/__tests__/db.contract.test.ts
describe('module-datalayer contract', () => {
  it('exports UserRepository class', async () => {
    const { UserRepository } = await import('../db/repositories/UserRepository');
    expect(typeof UserRepository).toBe('function');
  });
  it('UserRepository has required CRUD methods', async () => {
    const { UserRepository } = await import('../db/repositories/UserRepository');
    const proto = UserRepository.prototype as Record<string, unknown>;
    ['findById', 'findByEmail', 'create', 'update', 'delete', 'list'].forEach(m => {
      expect(typeof proto[m]).toBe('function');
    });
  });
  it('db client exports connect/disconnect', async () => {
    const mod = await import('../db/client');
    expect(typeof mod.connectDb).toBe('function');
    expect(typeof mod.disconnectDb).toBe('function');
  });
});
`;
}

export class DatalayerGenerator implements IModuleGenerator {
  readonly manifest: IModuleManifest = MANIFEST;

  async generate(reader: IBlueprintReader, api: IGeneratorAPI): Promise<ArtifactBundle> {
    const input = reader.getScaffoldInput();
    const files: ArtifactFile[] = [];

    const migration = file('prisma/migrations/0001_initial.sql',
      `-- Migration: 0001_initial\nCREATE TABLE IF NOT EXISTS "users" ("id" TEXT NOT NULL PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "name" TEXT, "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(), "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW());\nCREATE TABLE IF NOT EXISTS "audit_logs" ("id" TEXT NOT NULL PRIMARY KEY, "entity_type" TEXT NOT NULL, "entity_id" TEXT NOT NULL, "action" TEXT NOT NULL, "user_id" TEXT, "metadata" JSONB, "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW());\n`);

    const fileMap: Record<string, string> = {
      'prisma/schema.prisma':                   buildPrismaSchema(input.database),
      'src/db/client.ts':                       buildDbClient(input.database),
      'src/db/repositories/UserRepository.ts':  buildUserRepository(),
    };

    for (const [path, content] of Object.entries(fileMap)) {
      await api.writeFile(path, content);
      files.push(file(path, content));
    }
    await api.writeFile(migration.path, migration.content);

    const testContent = buildDatalayerTest();
    await api.writeFile('src/__tests__/db.contract.test.ts', testContent);

    return {
      files,
      testFiles: [file('src/__tests__/db.contract.test.ts', testContent)],
      dbMigrations: [migration],
      k8sManifests: [],
      docFiles: [],
      knowledgeArtifact: {
        moduleName: 'module-datalayer',
        version: MANIFEST.version,
        generatedAt: new Date().toISOString(),
        domainDescription: `Database access layer using Prisma ORM with ${input.database}.`,
        entities: [
          { name: 'User', filePath: 'prisma/schema.prisma', fields: [{ name: 'id', type: 'string', optional: false }, { name: 'email', type: 'string', optional: false }, { name: 'name', type: 'string', optional: true }] },
          { name: 'AuditLog', filePath: 'prisma/schema.prisma', fields: [{ name: 'id', type: 'string', optional: false }, { name: 'entityType', type: 'string', optional: false }, { name: 'action', type: 'string', optional: false }] },
        ],
        endpoints: [],
        emittedEvents: [],
        consumedEvents: [],
        invariants: [{ description: 'All DB access goes through typed Prisma repositories', source: 'annotation', filePath: 'src/db/repositories/UserRepository.ts' }],
        extensionPoints: [{ hookName: 'addRepository', filePath: 'src/db/repositories/', description: 'Create typed repository for each Prisma model' }],
        userFlows: [],
        glossary: [{ term: 'Repository', definition: 'A typed class wrapping Prisma queries for a specific model' }],
        exampleUsages: [],
      },
      signature: '',
    };
  }

  validate(bundle: ArtifactBundle): ValidationResult {
    const errors: Array<{ code: string; message: string }> = [];
    if (!bundle.files.find(f => f.path.includes('schema.prisma'))) errors.push({ code: 'MISSING_SCHEMA', message: 'Prisma schema required' });
    if (bundle.dbMigrations.length === 0) errors.push({ code: 'MISSING_MIGRATIONS', message: 'At least one migration required' });
    if (bundle.testFiles.length === 0) errors.push({ code: 'MISSING_TESTS', message: 'Contract test required' });
    return { valid: errors.length === 0, errors, warnings: [] };
  }
}

export default DatalayerGenerator;
