/**
 * @oweibo/module-codegen
 *
 * Generates the core application code: Express/Next.js entry points,
 * route handlers, middleware, API controllers, and typed request/response
 * schemas (Zod). Runs after module-scaffolding.
 *
 * Implements IModuleGenerator (core-contracts only — no core-engine imports).
 */
import type {
  IModuleGenerator,
  IModuleManifest,
  IBlueprintReader,
  IGeneratorAPI,
  ArtifactBundle,
  ArtifactFile,
  ValidationResult,
} from '@oweibo/core-contracts';
import { createHash } from 'crypto';

function checksum(content: string): string {
  return createHash('sha256').update(content, 'utf-8').digest('hex');
}
function file(path: string, content: string): ArtifactFile {
  return { path, content, encoding: 'utf-8', checksum: checksum(content) };
}

const MANIFEST: IModuleManifest = {
  name: 'module-codegen',
  version: '0.1.0',
  coreContractsVersion: '>=0.1.0',
  emits: ['codegen:completed'],
  consumes: ['scaffolding:completed'],
  knowledgeArtifactPath: 'knowledge/module-codegen.json',
};

function buildExpressApp(appName: string): string {
  return `// src/app.ts — generated by oweibo module-codegen
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import healthRouter from './routes/health.js';

export function createApp(): express.Application {
  const app = express();
  app.use(helmet());
  app.use(cors());
  app.use(express.json({ limit: '1mb' }));
  app.use(express.urlencoded({ extended: true }));
  app.use('/', healthRouter);
  app.use((_req, res) => { res.status(404).json({ error: 'not_found' }); });
  app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    console.error('[${appName}] Unhandled error:', err.message);
    res.status(500).json({ error: 'internal_error' });
  });
  return app;
}
`;
}

function buildExpressIndex(): string {
  return `// src/index.ts — generated by oweibo module-codegen
import { createApp } from './app.js';
const PORT = parseInt(process.env.PORT ?? '3000', 10);
const app = createApp();
app.listen(PORT, () => { console.log(\`Server running on port \${PORT}\`); });
export { app };
`;
}

function buildZodSchemas(): string {
  return `// src/schemas/index.ts — generated by oweibo module-codegen
import { z } from 'zod';

export const PaginationSchema = z.object({
  page:  z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});
export type Pagination = z.infer<typeof PaginationSchema>;

export interface ApiResponse<T> {
  data: T;
  meta?: { page?: number; limit?: number; total?: number };
  error?: string;
}

export function ok<T>(data: T, meta?: ApiResponse<T>['meta']): ApiResponse<T> {
  return { data, meta };
}
export function err(message: string): ApiResponse<never> {
  return { data: undefined as never, error: message };
}
`;
}

function buildValidateMiddleware(): string {
  return `// src/middleware/validate.ts — generated by oweibo module-codegen
import type { Request, Response, NextFunction } from 'express';
import type { ZodSchema, ZodError } from 'zod';

export function validate<T>(schema: ZodSchema<T>, source: 'body' | 'query' | 'params' = 'body') {
  return (req: Request, res: Response, next: NextFunction): void => {
    const result = schema.safeParse(req[source]);
    if (!result.success) {
      const details = (result.error as ZodError).errors.map(e => ({ field: e.path.join('.'), message: e.message }));
      res.status(400).json({ error: 'validation_error', details });
      return;
    }
    (req as Request & { validated: T }).validated = result.data;
    next();
  };
}
`;
}

function buildCodegenTest(appName: string): string {
  return `// src/__tests__/app.contract.test.ts
import request from 'supertest';
import { createApp } from '../app';

describe('${appName} API contract', () => {
  const app = createApp();

  it('GET /health returns 200 with status ok', async () => {
    const res = await request(app).get('/health');
    expect(res.status).toBe(200);
    expect(res.body).toMatchObject({ status: 'ok' });
  });

  it('unknown routes return 404', async () => {
    const res = await request(app).get('/nonexistent-route-xyz');
    expect(res.status).toBe(404);
  });
});
`;
}

export class CodegenGenerator implements IModuleGenerator {
  readonly manifest: IModuleManifest = MANIFEST;

  async generate(reader: IBlueprintReader, api: IGeneratorAPI): Promise<ArtifactBundle> {
    const input = reader.getScaffoldInput();
    const files: ArtifactFile[] = [];

    const fileMap: Record<string, string> = {
      'src/schemas/index.ts':      buildZodSchemas(),
      'src/middleware/validate.ts': buildValidateMiddleware(),
      'src/app.ts':                buildExpressApp(input.appName),
      'src/index.ts':              buildExpressIndex(),
    };

    for (const [path, content] of Object.entries(fileMap)) {
      await api.writeFile(path, content);
      files.push(file(path, content));
    }

    const testContent = buildCodegenTest(input.appName);
    await api.writeFile('src/__tests__/app.contract.test.ts', testContent);

    return {
      files,
      testFiles: [file('src/__tests__/app.contract.test.ts', testContent)],
      dbMigrations: [],
      k8sManifests: [],
      docFiles: [],
      knowledgeArtifact: {
        moduleName: 'module-codegen',
        version: MANIFEST.version,
        generatedAt: new Date().toISOString(),
        domainDescription: 'Core application code: entry point, middleware, route handlers, and Zod schemas.',
        entities: [],
        endpoints: [{ method: 'GET', path: '/health', filePath: 'src/routes/health.ts' }],
        emittedEvents: [],
        consumedEvents: [],
        invariants: [{ description: 'All request bodies validated with Zod before handler execution', source: 'annotation', filePath: 'src/middleware/validate.ts' }],
        extensionPoints: [{ hookName: 'registerRoutes', filePath: 'src/app.ts', description: 'Add new routers to the Express app' }],
        userFlows: [],
        glossary: [{ term: 'Validation middleware', definition: 'Automatic Zod schema validation on incoming requests' }],
        exampleUsages: [],
      },
      signature: '',
    };
  }

  validate(bundle: ArtifactBundle): ValidationResult {
    const errors: Array<{ code: string; message: string }> = [];
    if (bundle.files.length === 0) errors.push({ code: 'EMPTY_BUNDLE', message: 'Codegen produced no files' });
    if (bundle.testFiles.length === 0) errors.push({ code: 'MISSING_TESTS', message: 'At least one contract test is required' });
    return { valid: errors.length === 0, errors, warnings: [] };
  }
}

export default CodegenGenerator;
