/**
 * @oweibo/module-observability
 *
 * Generates the observability layer: Prometheus metrics exposition,
 * Winston structured logger, Grafana dashboard JSON, and OpenTelemetry
 * trace exporter config. Runs after module-codegen.
 *
 * Implements IModuleGenerator (core-contracts only — no core-engine imports).
 */
import type {
  IModuleGenerator,
  IModuleManifest,
  IBlueprintReader,
  IGeneratorAPI,
  ArtifactBundle,
  ArtifactFile,
  ValidationResult,
} from '@oweibo/core-contracts';
import { createHash } from 'crypto';

function checksum(c: string): string { return createHash('sha256').update(c, 'utf-8').digest('hex'); }
function file(path: string, content: string): ArtifactFile {
  return { path, content, encoding: 'utf-8', checksum: checksum(content) };
}

const MANIFEST: IModuleManifest = {
  name: 'module-observability',
  version: '0.1.0',
  coreContractsVersion: '>=0.1.0',
  emits: ['observability:completed'],
  consumes: ['codegen:completed'],
  knowledgeArtifactPath: 'knowledge/module-observability.json',
};

function buildMetricsMiddleware(appName: string): string {
  return `// src/observability/metrics.ts — generated by oweibo module-observability
import { Registry, Counter, Histogram, Gauge, collectDefaultMetrics } from 'prom-client';
import type { Request, Response, NextFunction } from 'express';

export const register = new Registry();
register.setDefaultLabels({ app: '${appName.toLowerCase().replace(/\s+/g, '-')}' });
collectDefaultMetrics({ register });

export const httpRequestsTotal = new Counter({
  name: 'http_requests_total',
  help: 'Total number of HTTP requests',
  labelNames: ['method', 'route', 'status_code'] as const,
  registers: [register],
});

export const httpRequestDurationMs = new Histogram({
  name: 'http_request_duration_ms',
  help: 'HTTP request duration in milliseconds',
  labelNames: ['method', 'route', 'status_code'] as const,
  buckets: [5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000],
  registers: [register],
});

export const activeConnections = new Gauge({
  name: 'http_active_connections',
  help: 'Number of active HTTP connections',
  registers: [register],
});

export const taskQueueDepth = new Gauge({
  name: 'oweibo_task_queue_depth',
  help: 'Number of tasks currently queued for processing',
  labelNames: ['tenant_id'] as const,
  registers: [register],
});

export const llmCallsTotal = new Counter({
  name: 'oweibo_llm_calls_total',
  help: 'Total LLM API calls',
  labelNames: ['model', 'stage', 'status'] as const,
  registers: [register],
});

export const llmTokensUsed = new Counter({
  name: 'oweibo_llm_tokens_total',
  help: 'Total tokens consumed by LLM calls',
  labelNames: ['model', 'type'] as const,
  registers: [register],
});

/** Express middleware that records latency and status for every request. */
export function metricsMiddleware(req: Request, res: Response, next: NextFunction): void {
  const start = Date.now();
  activeConnections.inc();
  res.on('finish', () => {
    const duration = Date.now() - start;
    const route = (req.route?.path as string | undefined) ?? req.path;
    const labels = { method: req.method, route, status_code: String(res.statusCode) };
    httpRequestsTotal.inc(labels);
    httpRequestDurationMs.observe(labels, duration);
    activeConnections.dec();
  });
  next();
}

/** Route handler for GET /metrics — returns Prometheus text format. */
export async function metricsHandler(req: Request, res: Response): Promise<void> {
  try {
    res.set('Content-Type', register.contentType);
    res.end(await register.metrics());
  } catch (err) {
    res.status(500).end(String(err));
  }
}
`;
}

function buildLogger(appName: string): string {
  return `// src/observability/logger.ts — generated by oweibo module-observability
import { createLogger, format, transports } from 'winston';
import type { Logger } from 'winston';

const { combine, timestamp, json, errors, colorize, simple } = format;

const isDev = process.env.NODE_ENV === 'development';

export const logger: Logger = createLogger({
  level: process.env.LOG_LEVEL ?? (isDev ? 'debug' : 'info'),
  defaultMeta: { service: '${appName.toLowerCase().replace(/\s+/g, '-')}' },
  format: isDev
    ? combine(colorize(), timestamp(), simple())
    : combine(errors({ stack: true }), timestamp(), json()),
  transports: [
    new transports.Console(),
  ],
  exitOnError: false,
});

/** Child logger scoped to a specific module/context. */
export function childLogger(context: string): Logger {
  return logger.child({ context });
}

/** Log an error with structured metadata. */
export function logError(err: unknown, context?: Record<string, unknown>): void {
  if (err instanceof Error) {
    logger.error(err.message, { stack: err.stack, ...context });
  } else {
    logger.error(String(err), context);
  }
}

export default logger;
`;
}

function buildGrafanaDashboard(appName: string): string {
  const safeName = appName.toLowerCase().replace(/\s+/g, '-');
  return JSON.stringify({
    __inputs: [],
    __requires: [{ type: 'grafana', id: 'grafana', name: 'Grafana', version: '10.0.0' }],
    annotations: { list: [] },
    editable: true,
    fiscalYearStartMonth: 0,
    graphTooltip: 0,
    id: null,
    links: [],
    panels: [
      {
        datasource: { type: 'prometheus', uid: '${DS_PROMETHEUS}' },
        fieldConfig: { defaults: { color: { mode: 'palette-classic' }, unit: 'reqps' }, overrides: [] },
        gridPos: { h: 8, w: 12, x: 0, y: 0 },
        id: 1,
        options: { legend: { calcs: [], displayMode: 'list', placement: 'bottom' }, tooltip: { mode: 'single' } },
        targets: [{
          datasource: { type: 'prometheus', uid: '${DS_PROMETHEUS}' },
          expr: `rate(http_requests_total{app="${safeName}"}[5m])`,
          legendFormat: '{{method}} {{route}} {{status_code}}',
          refId: 'A',
        }],
        title: 'HTTP Request Rate',
        type: 'timeseries',
      },
      {
        datasource: { type: 'prometheus', uid: '${DS_PROMETHEUS}' },
        fieldConfig: { defaults: { color: { mode: 'thresholds' }, thresholds: { mode: 'absolute', steps: [{ color: 'green', value: null }, { color: 'yellow', value: 500 }, { color: 'red', value: 1000 }] }, unit: 'ms' }, overrides: [] },
        gridPos: { h: 8, w: 12, x: 12, y: 0 },
        id: 2,
        options: { legend: { calcs: ['mean', 'p95', 'p99'], displayMode: 'table', placement: 'bottom' } },
        targets: [{
          datasource: { type: 'prometheus', uid: '${DS_PROMETHEUS}' },
          expr: `histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket{app="${safeName}"}[5m])) by (le, route))`,
          legendFormat: 'p95 {{route}}',
          refId: 'A',
        }],
        title: 'HTTP Latency p95',
        type: 'timeseries',
      },
      {
        datasource: { type: 'prometheus', uid: '${DS_PROMETHEUS}' },
        fieldConfig: { defaults: { unit: 'short' }, overrides: [] },
        gridPos: { h: 4, w: 6, x: 0, y: 8 },
        id: 3,
        options: { colorMode: 'value', graphMode: 'area', justifyMode: 'auto', orientation: 'auto', reduceOptions: { calcs: ['lastNotNull'] } },
        targets: [{
          datasource: { type: 'prometheus', uid: '${DS_PROMETHEUS}' },
          expr: `oweibo_task_queue_depth{app="${safeName}"}`,
          legendFormat: '{{tenant_id}}',
          refId: 'A',
        }],
        title: 'Task Queue Depth',
        type: 'stat',
      },
      {
        datasource: { type: 'prometheus', uid: '${DS_PROMETHEUS}' },
        fieldConfig: { defaults: { unit: 'short' }, overrides: [] },
        gridPos: { h: 4, w: 6, x: 6, y: 8 },
        id: 4,
        options: { colorMode: 'value', graphMode: 'area', justifyMode: 'auto', orientation: 'auto', reduceOptions: { calcs: ['lastNotNull'] } },
        targets: [{
          datasource: { type: 'prometheus', uid: '${DS_PROMETHEUS}' },
          expr: `rate(oweibo_llm_calls_total{app="${safeName}"}[5m])`,
          legendFormat: '{{model}} {{stage}}',
          refId: 'A',
        }],
        title: 'LLM Call Rate',
        type: 'stat',
      },
    ],
    refresh: '30s',
    schemaVersion: 38,
    tags: ['oweibo', 'generated', safeName],
    templating: { list: [] },
    time: { from: 'now-1h', to: 'now' },
    timepicker: {},
    timezone: 'browser',
    title: `${appName} — oweibo`,
    uid: checksum(safeName).slice(0, 16),
    version: 1,
  }, null, 2);
}

function buildPrometheusConfig(appName: string): string {
  const safeName = appName.toLowerCase().replace(/\s+/g, '-');
  return `# prometheus.yml — generated by oweibo module-observability
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    app: ${safeName}
    environment: '\${NODE_ENV:-development}'

scrape_configs:
  - job_name: '${safeName}'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
`;
}

function buildOtelConfig(): string {
  return `// src/observability/tracing.ts — generated by oweibo module-observability
// OpenTelemetry SDK bootstrap — must be imported before any other module.
import { NodeSDK } from '@opentelemetry/sdk-node';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { Resource } from '@opentelemetry/resources';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';

const sdk = new NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: process.env.OTEL_SERVICE_NAME ?? 'oweibo-app',
    [SemanticResourceAttributes.SERVICE_VERSION]: process.env.npm_package_version ?? '0.1.0',
  }),
  traceExporter: new OTLPTraceExporter({
    url: process.env.OTEL_EXPORTER_OTLP_ENDPOINT ?? 'http://localhost:4318/v1/traces',
  }),
  instrumentations: [
    getNodeAutoInstrumentations({
      '@opentelemetry/instrumentation-http': { enabled: true },
      '@opentelemetry/instrumentation-express': { enabled: true },
    }),
  ],
});

if (process.env.OTEL_ENABLED === 'true') {
  sdk.start();
  process.on('SIGTERM', () => { sdk.shutdown().finally(() => process.exit(0)); });
}

export { sdk };
`;
}

function buildHealthWithMetrics(): string {
  return `// src/routes/metrics.ts — generated by oweibo module-observability
import { Router } from 'express';
import { metricsHandler } from '../observability/metrics.js';

const router = Router();

/**
 * GET /metrics
 * Prometheus-compatible text format metrics endpoint.
 * Should be restricted to internal/ops network in production.
 */
router.get('/metrics', metricsHandler);

export default router;
`;
}

function buildObservabilityTest(): string {
  return `// src/__tests__/observability.contract.test.ts
describe('module-observability contract', () => {
  it('exports metricsMiddleware function', async () => {
    const mod = await import('../observability/metrics');
    expect(typeof mod.metricsMiddleware).toBe('function');
  });

  it('exports metricsHandler function', async () => {
    const mod = await import('../observability/metrics');
    expect(typeof mod.metricsHandler).toBe('function');
  });

  it('exports logger from logger module', async () => {
    const mod = await import('../observability/logger');
    expect(mod.logger).toBeDefined();
    expect(typeof mod.childLogger).toBe('function');
    expect(typeof mod.logError).toBe('function');
  });

  it('prometheus register has default metrics', async () => {
    const { register } = await import('../observability/metrics');
    const metrics = await register.metrics();
    expect(metrics).toContain('process_cpu_seconds_total');
  });
});
`;
}

export class ObservabilityGenerator implements IModuleGenerator {
  readonly manifest: IModuleManifest = MANIFEST;

  async generate(reader: IBlueprintReader, api: IGeneratorAPI): Promise<ArtifactBundle> {
    const input = reader.getScaffoldInput();
    const appName = input.appName;
    const files: ArtifactFile[] = [];

    const fileMap: Record<string, string> = {
      'src/observability/metrics.ts':   buildMetricsMiddleware(appName),
      'src/observability/logger.ts':    buildLogger(appName),
      'src/observability/tracing.ts':   buildOtelConfig(),
      'src/routes/metrics.ts':          buildHealthWithMetrics(),
      'grafana/dashboard.json':         buildGrafanaDashboard(appName),
      'prometheus.yml':                 buildPrometheusConfig(appName),
    };

    for (const [path, content] of Object.entries(fileMap)) {
      await api.writeFile(path, content);
      files.push(file(path, content));
    }

    const testContent = buildObservabilityTest();
    await api.writeFile('src/__tests__/observability.contract.test.ts', testContent);

    return {
      files,
      testFiles: [file('src/__tests__/observability.contract.test.ts', testContent)],
      dbMigrations: [],
      k8sManifests: [],
      docFiles: [],
      knowledgeArtifact: {
        moduleName: 'module-observability',
        version: MANIFEST.version,
        generatedAt: new Date().toISOString(),
        domainDescription: `Observability layer: Prometheus metrics exposition, Winston structured logging, Grafana dashboard, and OpenTelemetry trace export.`,
        entities: [],
        endpoints: [{ method: 'GET', path: '/metrics', filePath: 'src/routes/metrics.ts', description: 'Prometheus metrics endpoint' }],
        emittedEvents: [],
        consumedEvents: [],
        invariants: [
          { description: 'All HTTP requests must be instrumented via metricsMiddleware', source: 'annotation', filePath: 'src/observability/metrics.ts' },
          { description: '/metrics endpoint must be accessible for Prometheus scraping', source: 'annotation', filePath: 'src/routes/metrics.ts' },
        ],
        extensionPoints: [
          { hookName: 'addCustomMetric', filePath: 'src/observability/metrics.ts', description: 'Register additional prom-client metrics (Counter, Histogram, Gauge)' },
          { hookName: 'addOtelInstrumentation', filePath: 'src/observability/tracing.ts', description: 'Add OpenTelemetry auto-instrumentation libraries' },
        ],
        userFlows: [
          { name: 'Observe system health', actor: 'DevOps', steps: ['Prometheus scrapes /metrics every 15s', 'Grafana queries Prometheus', 'Dashboard shows request rate & latency'], outcome: 'Real-time system visibility' },
        ],
        glossary: [
          { term: 'prom-client', definition: 'Node.js Prometheus client library for metrics exposition' },
          { term: 'OTLP', definition: 'OpenTelemetry Protocol — standard format for trace/metric/log export' },
        ],
        exampleUsages: [],
      },
      signature: '',
    };
  }

  validate(bundle: ArtifactBundle): ValidationResult {
    const errors: Array<{ code: string; message: string }> = [];
    if (bundle.files.length === 0) errors.push({ code: 'EMPTY_BUNDLE', message: 'Observability module produced no files' });
    if (!bundle.files.find(f => f.path.includes('metrics.ts'))) errors.push({ code: 'MISSING_METRICS', message: 'Prometheus metrics module required' });
    if (!bundle.files.find(f => f.path.includes('logger.ts'))) errors.push({ code: 'MISSING_LOGGER', message: 'Logger module required' });
    if (!bundle.files.find(f => f.path.includes('dashboard.json'))) errors.push({ code: 'MISSING_DASHBOARD', message: 'Grafana dashboard JSON required' });
    if (bundle.testFiles.length === 0) errors.push({ code: 'MISSING_TESTS', message: 'Contract test required' });
    return { valid: errors.length === 0, errors, warnings: [] };
  }
}

export default ObservabilityGenerator;
