/**
 * Task 4.2: Gate 8A (Deterministic Invariants).
 * Reads deterministic invariants from memory and executes them as pytest
 * assertions within the container sandbox against the current workspace scope.
 * Zero-LLM implementation.
 * 
 * @module services/gates/invariantDeterministic
 */

const fs = require('fs');
const path = require('path');
const logger = require('../logger');
const metrics = require('../metrics');
const sandboxClient = require('../sandbox');

/**
 * Evaluate deterministic invariants.
 * Compiles the templates into pytest files and executes them.
 * 
 * @paramtaskId 
 * @paramcontainerId 
 * @paraminvariants - Invariants with type=='det'
 * @paramscope - List of changed files
 * @returns
 */
async function evaluateDeterministic(taskId, containerId, invariants, scope) {
    if (!invariants || invariants.length === 0) {
        logger.debug('Gate 8A passed vacuously (no deterministic invariants)');
        return { passed: true, violations: [], passedInvariantIds: [], failedInvariantIds: [] };
    }

    // Filter invariants relevant to the current file scope
    // For MVP, we assume all deterministic invariants are run, or we'd filter by scope metadata
    const activeInvariants = invariants;

    if (activeInvariants.length === 0) {
        return { passed: true, violations: [] };
    }

    logger.info(`Evaluating Gate 8A (${activeInvariants.length} invariants)`, { task_id: taskId });
    const violations = [];

    // Write assertions to a test file that will be mounted/accessible by the container
    const cacheDir = '/var/kilo/assertion_cache';
    fs.mkdirSync(cacheDir, { recursive: true });

    const testFileHost = path.join(cacheDir, `test_gate8a_${taskId}.py`);
    const testFileContainer = `/tmp/test_gate8a_${taskId}.py`;

    let pythonCode = `import pytest\nimport os\n\n# Auto-generated by kilo-pipeline Gate 8A\n`;

    activeInvariants.forEach((inv, i) => {
        if (inv.assertion_template) {
            pythonCode += `def test_invariant_${i}():\n`;
            // Indent the template
            const indentedTemplate = inv.assertion_template.split('\n').map(l => `    ${l}`).join('\n');
            pythonCode += `${indentedTemplate}\n\n`;
        }
    });

    fs.writeFileSync(testFileHost, pythonCode);

    // In a real Docker bind mount, /var/kilo/assertion_cache must be mounted to /tmp/ in the sandbox
    // Alternatively, we inject it via docker exec
    try {
        const injectCmd = ['sh', '-c', `echo "${pythonCode.replace(/"/g, '\\"')}" > ${testFileContainer}`];
        await sandboxClient.execInSandbox(containerId, injectCmd);

        // Run pytest
        // We expect exit code 0 if all assertions pass
        const pytestCmd = ['pytest', testFileContainer];
        const result = await sandboxClient.execInSandbox(containerId, pytestCmd);

        // All invariant IDs passed (Gate 8A is pass/fail on the whole suite, not per-invariant)
        const allIds = activeInvariants.map(inv => inv.id).filter(Boolean);

        if (result.exitCode !== 0) {
            metrics.gateFailureCount.inc({ gate: 'G8A', tier: 'T1' });
            logger.warn('Gate 8A failed', { task_id: taskId, exitCode: result.exitCode });
            const lines = result.stdout.split('\n');
            const failLines = lines.filter(l => l.includes('FAILED') || l.includes('AssertionError'));
            violations.push(...failLines.map(l => l.trim()));

            return {
                passed: false,
                violations: violations.length ? violations : ['Pytest execution failed'],
                passedInvariantIds: [],
                failedInvariantIds: allIds,
            };
        }

        logger.info('Gate 8A passed', { task_id: taskId });
        return { passed: true, violations: [], passedInvariantIds: allIds, failedInvariantIds: [] };

    } catch (err) {
        metrics.gateFailureCount.inc({ gate: 'G8A', tier: 'T1' });
        logger.error('Gate 8A execution error', { task_id: taskId, error: err.message });
        const allIds = activeInvariants.map(inv => inv.id).filter(Boolean);
        return {
            passed: false,
            violations: [`Gate 8A internal error: ${err.message}`],
            passedInvariantIds: [],
            failedInvariantIds: allIds,
        };
    }
}

module.exports = { evaluateDeterministic };

export {};
