---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: oweibo
data:
  traefik.yaml: |
    global:
      checkNewVersion: true
      sendAnonymousUsage: false

    api:
      dashboard: true
      insecure: true

    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https

      websecure:
        address: ":443"

      metrics:
        address: ":8082"

    metrics:
      prometheus:
        entryPoint: metrics

    providers:
      kubernetesIngress:
        enabled: true
      file:
        filename: /etc/traefik/dynamic.yaml
        watch: true
