apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: oweibo
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: dashboard
      port: 8080
      targetPort: dashboard
      protocol: TCP
