/**
 * @oweibo/module-export
 *
 * Generates the Export & Packaging layer: signed Docker image manifests,
 * SQL dump scripts, K8s production overlays, Helm chart skeletons, and
 * HMAC-SHA256 bundle signatures for artifact integrity verification.
 *
 * Implements IModuleGenerator (core-contracts only — no core-engine imports).
 */
import type {
  IModuleGenerator,
  IModuleManifest,
  IBlueprintReader,
  IGeneratorAPI,
  ArtifactBundle,
  ArtifactFile,
  ValidationResult,
} from '@oweibo/core-contracts';
import { createHash, createHmac } from 'crypto';

function checksum(c: string): string { return createHash('sha256').update(c, 'utf-8').digest('hex'); }
function file(path: string, content: string): ArtifactFile {
  return { path, content, encoding: 'utf-8', checksum: checksum(content) };
}

const MANIFEST: IModuleManifest = {
  name: 'module-export',
  version: '0.1.0',
  coreContractsVersion: '>=0.1.0',
  emits: ['export:completed'],
  consumes: ['codegen:completed', 'datalayer:completed', 'auth:completed'],
  knowledgeArtifactPath: 'knowledge/module-export.json',
};

function buildDockerManifest(appName: string, registry: string): string {
  const safeName = appName.toLowerCase().replace(/\s+/g, '-');
  return JSON.stringify({
    schemaVersion: 2,
    mediaType: 'application/vnd.docker.distribution.manifest.v2+json',
    config: {
      mediaType: 'application/vnd.docker.container.image.v1+json',
      size: 0,
      digest: `sha256:${'0'.repeat(64)}`,
    },
    layers: [],
    annotations: {
      'org.opencontainers.image.title': safeName,
      'org.opencontainers.image.version': '0.1.0',
      'org.opencontainers.image.source': `${registry}/${safeName}`,
      'org.opencontainers.image.created': new Date().toISOString(),
      'com.oweibo.generated': 'true',
    },
  }, null, 2);
}

function buildDockerignore(): string {
  return `node_modules/
dist/
.env
.env.*
!.env.example
coverage/
.next/
*.log
.DS_Store
*.test.ts
*.spec.ts
__tests__/
`;
}

function buildSqlDumpScript(database: string): string {
  if (database === 'sqlite') {
    return `#!/usr/bin/env bash
# dump.sh — SQLite export script generated by oweibo module-export
set -euo pipefail

DB_FILE="\${DB_FILE:-./prisma/dev.db}"
OUTPUT_DIR="\${OUTPUT_DIR:-./exports}"
TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
OUTPUT_FILE="\${OUTPUT_DIR}/dump_\${TIMESTAMP}.sql"

mkdir -p "\${OUTPUT_DIR}"
sqlite3 "\${DB_FILE}" .dump > "\${OUTPUT_FILE}"
echo "[export] SQLite dump written to \${OUTPUT_FILE}"
`;
  }
  return `#!/usr/bin/env bash
# dump.sh — PostgreSQL export script generated by oweibo module-export
set -euo pipefail

DATABASE_URL="\${DATABASE_URL:?DATABASE_URL is required}"
OUTPUT_DIR="\${OUTPUT_DIR:-./exports}"
TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
OUTPUT_FILE="\${OUTPUT_DIR}/dump_\${TIMESTAMP}.sql"

mkdir -p "\${OUTPUT_DIR}"
pg_dump --no-owner --no-acl "\${DATABASE_URL}" > "\${OUTPUT_FILE}"
gzip "\${OUTPUT_FILE}"
echo "[export] Dump written to \${OUTPUT_FILE}.gz"
`;
}

function buildHelmChart(appName: string): string {
  const safeName = appName.toLowerCase().replace(/\s+/g, '-');
  return `# Chart.yaml — generated by oweibo module-export
apiVersion: v2
name: ${safeName}
description: Helm chart for ${appName}
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - oweibo
  - generated
maintainers:
  - name: oweibo
    email: platform@oweibo.dev
`;
}

function buildHelmValues(appName: string, registry: string): string {
  const safeName = appName.toLowerCase().replace(/\s+/g, '-');
  return `# values.yaml — generated by oweibo module-export
replicaCount: 2

image:
  repository: ${registry}/${safeName}
  pullPolicy: IfNotPresent
  tag: "0.1.0"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  NODE_ENV: production
  PORT: "3000"

envFrom:
  - secretRef:
      name: ${safeName}-secrets

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
`;
}

function buildHelmTemplateDeployment(appName: string): string {
  return `{{- /* deployment.yaml — generated by oweibo module-export */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
`;
}

function buildK8sProductionOverlay(appName: string, registry: string): string {
  const safeName = appName.toLowerCase().replace(/\s+/g, '-');
  return `# k8s/overlays/production/kustomization.yaml — generated by oweibo module-export
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${safeName}-prod
namePrefix: prod-
commonLabels:
  environment: production
  app.kubernetes.io/managed-by: oweibo
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: ${safeName}
images:
  - name: ${safeName}
    newName: ${registry}/${safeName}
    newTag: "0.1.0"
`;
}

function buildGithubActionsRelease(appName: string, registry: string): string {
  const safeName = appName.toLowerCase().replace(/\s+/g, '-');
  return `# .github/workflows/release.yml — generated by oweibo module-export
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ${registry}
  IMAGE_NAME: ${safeName}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: \${{ env.REGISTRY }}
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: \${{ steps.meta.outputs.tags }}
          labels: \${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run smoke test
        run: |
          docker run --rm -e NODE_ENV=test \\
            \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:\${{ github.ref_name }} \\
            node -e "require('./dist/index.js')" || exit 1
`;
}

function buildBundleSignScript(): string {
  return `#!/usr/bin/env node
// scripts/sign-bundle.js — generated by oweibo module-export
// Computes HMAC-SHA256 signature over all artifact files for integrity verification.
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SECRET = process.env.BUNDLE_SIGNING_SECRET;
if (!SECRET) { console.error('[sign-bundle] BUNDLE_SIGNING_SECRET env var required'); process.exit(1); }

const DIST_DIR = process.argv[2] ?? path.join(__dirname, '..', 'dist');
if (!fs.existsSync(DIST_DIR)) { console.error(\`[sign-bundle] Directory not found: \${DIST_DIR}\`); process.exit(1); }

function collectFiles(dir, base = dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const result = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) result.push(...collectFiles(full, base));
    else result.push(path.relative(base, full).replace(/\\\\/g, '/'));
  }
  return result;
}

const files = collectFiles(DIST_DIR);
const hmac = crypto.createHmac('sha256', SECRET);
for (const f of files) {
  const content = fs.readFileSync(path.join(DIST_DIR, f));
  hmac.update(\`\${f}:\`);
  hmac.update(content);
}
const signature = hmac.digest('hex');
const manifest = { version: '1', algorithm: 'hmac-sha256', files, signature, signedAt: new Date().toISOString() };
const outPath = path.join(DIST_DIR, 'bundle.sig.json');
fs.writeFileSync(outPath, JSON.stringify(manifest, null, 2));
console.log(\`[sign-bundle] Signature: \${signature}\`);
console.log(\`[sign-bundle] Manifest written to \${outPath}\`);
`;
}

function buildVerifyScript(): string {
  return `#!/usr/bin/env node
// scripts/verify-bundle.js — generated by oweibo module-export
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SECRET = process.env.BUNDLE_SIGNING_SECRET;
if (!SECRET) { console.error('[verify-bundle] BUNDLE_SIGNING_SECRET env var required'); process.exit(1); }

const SIG_FILE = process.argv[2] ?? path.join(__dirname, '..', 'dist', 'bundle.sig.json');
if (!fs.existsSync(SIG_FILE)) { console.error(\`[verify-bundle] Signature file not found: \${SIG_FILE}\`); process.exit(1); }

const manifest = JSON.parse(fs.readFileSync(SIG_FILE, 'utf-8'));
const distDir = path.dirname(SIG_FILE);
const hmac = crypto.createHmac('sha256', SECRET);
for (const f of manifest.files) {
  const filePath = path.join(distDir, f);
  if (!fs.existsSync(filePath)) { console.error(\`[verify-bundle] Missing file: \${f}\`); process.exit(2); }
  const content = fs.readFileSync(filePath);
  hmac.update(\`\${f}:\`);
  hmac.update(content);
}
const computed = hmac.digest('hex');
if (computed !== manifest.signature) {
  console.error(\`[verify-bundle] SIGNATURE MISMATCH\`);
  console.error(\`  expected: \${manifest.signature}\`);
  console.error(\`  computed: \${computed}\`);
  process.exit(3);
}
console.log('[verify-bundle] Bundle signature VALID');
`;
}

function buildExportTest(): string {
  return `// src/__tests__/export.contract.test.ts
describe('module-export contract', () => {
  it('bundle includes Dockerfile', async () => {
    expect(true).toBe(true); // placeholder — real test runs against generated bundle
  });

  it('bundle includes Helm chart', async () => {
    const { ExportGenerator } = await import('../index');
    expect(typeof ExportGenerator).toBe('function');
  });

  it('ExportGenerator has generate and validate methods', async () => {
    const { ExportGenerator } = await import('../index');
    const gen = new ExportGenerator();
    expect(typeof gen.generate).toBe('function');
    expect(typeof gen.validate).toBe('function');
  });
});
`;
}

export class ExportGenerator implements IModuleGenerator {
  readonly manifest: IModuleManifest = MANIFEST;

  async generate(reader: IBlueprintReader, api: IGeneratorAPI): Promise<ArtifactBundle> {
    const input = reader.getScaffoldInput();
    const appName = input.appName;
    const registry = ((input as unknown as Record<string, unknown>)['containerRegistry'] as string | undefined) ?? 'ghcr.io/oweibo';
    const database = input.database ?? 'postgresql';
    const files: ArtifactFile[] = [];

    const fileMap: Record<string, string> = {
      'docker/manifest.json':                            buildDockerManifest(appName, registry),
      '.dockerignore':                                   buildDockerignore(),
      'scripts/dump.sh':                                 buildSqlDumpScript(database),
      'scripts/sign-bundle.js':                          buildBundleSignScript(),
      'scripts/verify-bundle.js':                        buildVerifyScript(),
      'helm/Chart.yaml':                                 buildHelmChart(appName),
      'helm/values.yaml':                                buildHelmValues(appName, registry),
      'helm/templates/deployment.yaml':                  buildHelmTemplateDeployment(appName),
      'k8s/overlays/production/kustomization.yaml':      buildK8sProductionOverlay(appName, registry),
      '.github/workflows/release.yml':                   buildGithubActionsRelease(appName, registry),
    };

    for (const [path, content] of Object.entries(fileMap)) {
      await api.writeFile(path, content);
      files.push(file(path, content));
    }

    // Compute deterministic bundle signature over all file paths + checksums
    const sigPayload = files.map(f => `${f.path}:${f.checksum}`).join('\n');
    const signature = createHmac('sha256', 'oweibo-internal-signing-seed').update(sigPayload).digest('hex');

    const testContent = buildExportTest();
    await api.writeFile('src/__tests__/export.contract.test.ts', testContent);

    const k8sManifests = [file('k8s/overlays/production/kustomization.yaml', fileMap['k8s/overlays/production/kustomization.yaml']!)];

    return {
      files,
      testFiles: [file('src/__tests__/export.contract.test.ts', testContent)],
      dbMigrations: [],
      k8sManifests,
      docFiles: [],
      knowledgeArtifact: {
        moduleName: 'module-export',
        version: MANIFEST.version,
        generatedAt: new Date().toISOString(),
        domainDescription: `Export & packaging layer: Docker manifests, Helm charts, K8s overlays, SQL dump scripts, and HMAC-signed artifact bundles.`,
        entities: [],
        endpoints: [],
        emittedEvents: [],
        consumedEvents: [],
        invariants: [
          { description: 'All artifact bundles must carry an HMAC-SHA256 signature', source: 'annotation', filePath: 'scripts/sign-bundle.js' },
          { description: 'Production K8s overlay must set replica count >= 2', source: 'annotation', filePath: 'k8s/overlays/production/kustomization.yaml' },
        ],
        extensionPoints: [
          { hookName: 'addHelmTemplate', filePath: 'helm/templates/', description: 'Add Helm template files for additional K8s resources' },
          { hookName: 'extendDockerfile', filePath: 'Dockerfile', description: 'Extend the generated Dockerfile with custom build steps' },
        ],
        userFlows: [
          { name: 'Release pipeline', actor: 'CI/CD', steps: ['git tag v1.0.0', 'push triggers release.yml', 'Docker image built & pushed', 'bundle signed'], outcome: 'Signed container image published to registry' },
          { name: 'Verify bundle integrity', actor: 'DevOps', steps: ['run scripts/verify-bundle.js'], outcome: 'Bundle signature validated' },
        ],
        glossary: [
          { term: 'Bundle signature', definition: 'HMAC-SHA256 digest over all artifact paths and their checksums, proving integrity' },
          { term: 'Helm chart', definition: 'Kubernetes package manager chart for deploying the application' },
        ],
        exampleUsages: [],
      },
      signature,
    };
  }

  validate(bundle: ArtifactBundle): ValidationResult {
    const errors: Array<{ code: string; message: string }> = [];
    if (bundle.files.length === 0) errors.push({ code: 'EMPTY_BUNDLE', message: 'Export module produced no files' });
    if (!bundle.files.find(f => f.path.includes('helm'))) errors.push({ code: 'MISSING_HELM', message: 'Helm chart is required for production export' });
    if (!bundle.files.find(f => f.path.includes('sign-bundle'))) errors.push({ code: 'MISSING_SIGN_SCRIPT', message: 'Bundle signing script is required' });
    if (bundle.testFiles.length === 0) errors.push({ code: 'MISSING_TESTS', message: 'Contract test required' });
    if (!bundle.signature) errors.push({ code: 'MISSING_SIGNATURE', message: 'Bundle must carry an HMAC signature' });
    return { valid: errors.length === 0, errors, warnings: [] };
  }
}

export default ExportGenerator;
